#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
 jpa:
    show-sql: true
    open-in-view: false
    # https://stackoverflow.com/a/67678945/548473
    defer-datasource-initialization: true
    #hibernate:
     # ddl-auto: create
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
 datasource:
    # postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

 data.rest:
  #  https://docs.spring.io/spring-data/rest/docs/current/reference/html/#getting-started.basic-settings
  basePath: /api
  returnBodyOnCreate: true

  # Jackson Serialization Issue Resolver
 jackson.visibility:
    field: any
    getter: none
    setter: none
    is-getter: none

 security:
   user.name: user # Default user name.
   user.password: 123  # Password

logging:
  level:
    root: WARN
    ru.morozov.graduation: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
    org.springframework.cache: TRACE


server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true

server:
  port: 8080
